# version: '3.8'

# services:

#   postgres:
#     image: postgres:16
#     container_name: auth-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Admin@123
#       POSTGRES_DB: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./initdb:/docker-entrypoint-initdb.d

#   keycloak:
#     image: quay.io/keycloak/keycloak:24.0
#     container_name: keycloak
#     command: start-dev
#     environment:
#       KC_DB: postgres
#       KC_DB_URL_HOST: postgres
#       KC_DB_URL_DATABASE: keycloak
#       KC_DB_USERNAME: postgres
#       KC_DB_PASSWORD: Admin@123

#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres

#   auth-service:
#     build: 
#       context: ../Java/auth-service
#       dockerfile: Dockerfile   # sửa đúng path của bạn
#     container_name: auth-service
#     depends_on:
#       - postgres
#       - keycloak
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: Admin@123

#       SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/myrealm
#     ports:
#       - "7001:8080"

# volumes:
#   postgres_data:

version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin@123
      MONGO_INITDB_DATABASE: socialdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: